### PR TITLE
Proposition to show all pandemics in all figures

### PR DESCRIPTION
**Pull request by jriou**
I thought it might be good to show all pandemics for all figures.

Advantages:
- highlights the fact that we checked many years and not only 1899 and 1918
- highlights the specificities of 1918 and 2020
- more coherent since we highlight these years in figure 1

Inconvenients:
- a bit busy maybe?

image

image

We can also stick to the plan it's just a last-minute idea that doesn't really change anything for the text.

### CODE REVIEW

**Comment by marcelzwahlen** [comment]
Perhaps to be put into the supplement

**Comment by kasparstaub** [comment]
great thanks so much! I agree, excellent for the supplementary material?

**Comment by jriou** [comment]
Ok fine :)

**Comment by jriou** [comment]
I guess the online version is enough, and avoids having to change all references to the supplementary :)

**Pull request closed without merging**
